apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mcp-gateway-registry
  app.kubernetes.io/part-of: mcp-gateway
  app.kubernetes.io/managed-by: kustomize
