apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::338293206254:role/eksctl-mcp-gateway-eks-cluster-addon-iamservi-Role1-LdWu6WSJHyBw