apiVersion: v1
kind: Pod
metadata:
  name: efs-test-pod4
  namespace: mcp-gateway
spec:
  containers:
  - name: efs-test
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "touch /data/success && echo 'EFS is working!' > /data/success && cat /data/success && sleep 3600"]
    volumeMounts:
    - name: efs-volume
      mountPath: /data
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: mcp-gateway-registry-pvc